language: python
python:
 - "3.5"
env:
- ACTION="run lint"
- ACTION="run dist" # ensures building dist files doesn't break
- ACTION="run test"
before_install:
- export PATH=$HOME/.local/bin:$PATH
- wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 6 # for Node v6
- node --version
- npm install
- curl https://raw.githubusercontent.com/Kinto/kinto/master/requirements.txt > versions.txt
- pip install https://github.com/Kinto/kinto/zipball/master --constraint versions.txt
- pip install kinto-attachment
- export KINTO_PSERVE_EXECUTABLE=pserve
script:
- npm $ACTION
after_script:
- npm run report-coverage
